### ISSUE TITLE
Integrate Local Device Support into AMTH

### ISSUE THREAD

**Issue by nodlesh** [hyperledger/aries-mobile-test-harness#19]
**STORY**
AS A tester for the BC wallet I WANT to be able to use a local real device to run tests against SO THAT I can debug problems in the device cloud or to do quick testing and verification without having the device cloud involved

**Acceptance Criteria:**
GIVEN the AMTH is setup and able to execute
WHEN I give the command manage run specifying local and bundelID details of my connected local device
THEN the AMTH will run tests against the connected local device

**Subtasks:**
- [ ] Get Appium Server and Appium inspector running with the local iOS device
- [x] Get Appium Server and Appium inspector running with the local Android device
- [x] Integrate local Android device with AMTH BC Wallet tests
- [ ] Can Vysor be used to automate a local connected devices easier than a dev env locally?
- [x] Determine config.json settings for local devices
- [x] Update manage script to allow local as an option 

**Questions:**
1. Should the Manage script start Appium Server locally? 
2. Should the manage script build a container for appium server? 
- Would only work for Android only. iOS would still need appium installed on mac.  iOS also needs Xcode installed. It is best to let the user manage this. (maybe Vysor changes this assumption)

**Comment by nodlesh** [comment]
Putting this aside for some focused test development. Here is an explanation of the state of affairs. 

Someone running with a local device or emulator/simulator needs a full dev environment on the system for Android and/or iOS. this includes xCode for iOS and Android Studio for Android. I was trying to dwindle the dev environment down for testing but that doesn't seem possible at this point. 

Forecasted run enhancements to AMTH
From 
```
LEDGER_URL_CONFIG=http://test.bcovrin.vonx.io REGION=us-west-1 ./manage run -d SauceLabs -u oauth-sheldon.regular-32de4 -k 4dba5e58-16c0-4532-b43e-4a543701610d -p Android -a app-release.apk -i acapy-main -v acapy-main -t @Connect
```
to 
```
LEDGER_URL_CONFIG=http://test.bcovrin.vonx.io REGION=us-west-1 ./manage run -d Local -c config.json -i acapy-main -v acapy-main -t @Connect
```

To verify what is needed or to check your local machine for installation requirements install Appium-doctor.
```
npm install -g appium-doctor
```

```
appium-doctor --ios 
appium-doctor --android
```

appium Config file that does still is not successful
```
{
  "platformName": "iOS",
  "appium:platformVersion": "15.0.2",
  "appium:deviceName": "iPhone 6s",
  "appium:udid": "auto",
  "appium:bundleId": "ca.bc.gov.BCWallet",
  "appium:xcodeOrgId": "L796QSLV3E",
  "appium:xcodeSigningId": "Apple Distribution: Her Majesty the Queen in right of the Province of British Columbia (L796QSLV3E)",
  "appium:updatedWDABundleId": "ca.bc.gov.*",
  "appium:automationName": "XCUITest"
}
```

References:
https://www.swtestacademy.com/how-to-install-appium-on-mac/
https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md
https://kobiton.com/book/chapter-5-the-ap
https://appiumpro.com/editions/40-how-to-test-on-real-ios-devices-with-appium-part-1pium-inspector-2
https://appiumpro.com/editions/41-how-to-test-real-ios-devices-with-appium-part-2
https://support.testsigma.com/support/solutions/articles/32000023784-using-appium-desktop-to-inspect-android-ios-apps-locally
https://support.testsigma.com/support/solutions/articles/32000023626-configuring-your-mac-and-ios-device-for-ios-native-test-execution
https://appium.io/docs/en/about-appium/getting-started/?lang=en
